# Generated by Django 4.0.4 on 2022-05-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='massage',
            field=models.ForeignKey(default=1652965485209, on_delete=django.db.models.deletion.CASCADE, to='programmming.massage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massage',
            name='comments',
            field=models.CharField(default=1652965485209, max_length=2500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=2500),
        ),
    ]
