# Generated by Django 4.0.4 on 2022-05-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0003_alter_massage_category_name_alter_massage_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='comments',
            field=models.CharField(blank=True, default=1652966179918, max_length=2500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='massage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
