# Generated by Django 4.0.4 on 2022-05-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0004_alter_massage_comments_alter_massage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='massage',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
    ]
