# Generated by Django 4.0.4 on 2022-05-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0006_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='user_comments',
        ),
        migrations.RenameField(
            model_name='massage',
            old_name='comments',
            new_name='user_comments',
        ),
    ]
