# Generated by Django 4.0.4 on 2022-05-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0007_rename_comments_comment_user_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_comments',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='massage',
            name='user_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmming.comment'),
        ),
    ]
