# Generated by Django 4.0.4 on 2022-05-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0008_alter_comment_user_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_comments',
        ),
        migrations.AlterField(
            model_name='massage',
            name='user_comments',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
