# Generated by Django 4.0.4 on 2022-05-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0012_remove_massage_user_comments_comment_user_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_comments',
        ),
        migrations.AddField(
            model_name='massage',
            name='user_comments',
            field=models.ForeignKey(default=1653132592263, on_delete=django.db.models.deletion.CASCADE, to='programmming.comment'),
            preserve_default=False,
        ),
    ]
