# Generated by Django 4.0.3 on 2022-05-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0014_remove_massage_user_comments_comment_user_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_comments',
        ),
    ]
