# Generated by Django 4.0.4 on 2022-05-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0016_alter_massage_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='answers',
            field=models.ForeignKey(default=1653384022035, on_delete=django.db.models.deletion.CASCADE, to='programmming.massage'),
            preserve_default=False,
        ),
    ]
