# Generated by Django 4.0.4 on 2022-05-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0017_remove_massage_comments_comment_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='programmming.massage'),
        ),
    ]
