# Generated by Django 4.0.4 on 2022-05-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0018_alter_comment_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='file',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=2500, null=True)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='programmming.massage')),
            ],
        ),
    ]
