# Generated by Django 4.0.4 on 2022-05-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0020_rename_file_files_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='programmming.massage'),
        ),
    ]
