# Generated by Django 4.0.4 on 2022-05-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0022_alter_files_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
