# Generated by Django 4.0.4 on 2022-05-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmming', '0023_rename_files_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=2500, null=True)),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
